#Loops in Python are used to execute a block of code repeatedly until a certain condition is met. The two main types of loops in Python are the "for" loop and the "while" loop.

#for loop is used to iterae over a sequence of iterable objects such as lists, tuples, strings, or ranges. It allows you to execute a block of code for each item in the sequence.

#for loop iterating over a string
print("Iterating over a string:")
name = 'Urja'
for letter in name:    #this loop prints each character of the string 'Urja' one by one
    print(letter)

#for loop iterating over a list  
print("\nIterating over a list:")
colors = ['red', 'green', 'blue']
for color in colors:    #this loop prints each color in the list one by one
    print(color)
    for char in color:    #this nested loop prints each character of the color one by one
        print(char)  

#range() - It is used to print a sequence of numbers. It can take one, two, or three arguments: start, stop, and step. The default start is 0, and the default step is 1.        
print("\nIterating over a range of values:")
for i in range(5): #this loop oprints a sequence of numbers 0 to 4 and omits 5.
    print(i)
print("\nIterating over a range with a specified start and stop:")
#for(i in range(1,5) - this loop prints a sequence of numbers from 1 to 4 and omits 5.Here start = 1 that tells the loop to start printing from 1 intead of default 0 value. Stop is 5 that tells the loop to stop printing at 5 and omit it. 
for i in range(1, 5):
    print(i)

#QUICK QUIZ - What does the third parameter(step) in the range() function do?

print("\nIterating over a range with a specified step:")
for i in range(1,10,2):
    print(i)
#The step parameter allows you to control the spacing between the numbers generated by the range() function. In this case, it starts at 1 and increments by 2, resulting in the odd numbers from 1 to 9.
#For example, if you use range(0, 10, 2), it will generate the numbers 0, 2, 4, 6, and 8, skipping every second number.